package model;

import model.BaseAskforleavesheet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Askforleavesheet extends BaseAskforleavesheet<Askforleavesheet> {
	public static final Askforleavesheet dao = new Askforleavesheet();
}
