package model;

import model.BaseOvertimesheet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Overtimesheet extends BaseOvertimesheet<Overtimesheet> {
	public static final Overtimesheet dao = new Overtimesheet();
}
